version: '2'
services:

  node:
    image: node
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon ; nodemon -e js,jade app.js'
    ports:
      - "80:3000"
    links:
      - mongo
    environment:
      MONGODB: "mongodb://mongo:27017/hackathon"

  mongo:
    image: mongo:2.6.11
    command: mongod --smallfiles
